### ISSUE TITLE
1.0.0 Checklist

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#41]
Here is a work in progress list of all tasks that need to be completed prior to the release of 1.0.0.

# Alpha (Released 10/20/2022 on `@next` tag on npm)
- [x] Typescript conversion and modernization efforts (#11, #12, #10, #9, #13)
- [x] New Material UI (#15)
- [x] New markdown editor (#35)

# Beta (Released 11/08/2022 on `@latest` tag on npm)
- [x] Full review of documentation (#20, #21)
- [x] Test Github backend
- [x] Test BitBucket backend - _Will not be supporting implicit flow going forward due to some redirect issues_
- [x] Test GitLab backend - _PKCE works, but there are some issues with Netlify authorization. Will look into after beta release_
- [x] ~~Test Azure backend~~ _Unable to test due to subscription requirement. Might drop support for Azure._
- [x] Test Git Gateway backend
- [x] Test Proxy backend
- [x] Test bundling setup
- [x] Test CDN setup
- [x] #25
- [x] #56
- [x] Open Bugs
   - [x] #55 
   - [x] #58 
   - [x] #60
   - [x] #66
   - [x] #70 
   - [x] Markdown preview not updating as you type
   - [x] Default date value not filling in entry
   - [x] Relation widget not saving

# Full Release
- [x] #81 (Markdown only)
- [x] Testing
  - [x] Test intregrations
    - [x] ~~Asset Store~~. _Dropping support for Asset Store_
    - [x] ~~Algolia (#31)~~. Dropping support
  - [x] Test Beta Features #47 
- [x] Documentation
  - [x] #72 
  - [x] NetlifyCMS migration guide (#46)
- [x] #54 
- [x] ~~Determine status of Azure support~~. _Dropping support for Azure_
- [x] #75
- [x] #18 
- [x] #242
- [x] Open Bugs
   - [x] #76 
   - [x] #77
   - [x] #79 

# Post Release
- [ ] #59
- [ ] Test Beta Features
   - [x] #62
   - [ ] #63 
   - [ ] #64 
   - [ ] #81 (MDX support)
- [ ] Testing
  - [ ] Test external media libraries
    - [ ] Cloudinary
    - [ ] UploadCare
  - [ ] Test Netlify Large Media
