### ISSUE TITLE
Integrate or Drop NetlifyCMS Beta Features

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#47]
Review all beta features and either fully integrate (especially around documentation) or drop each feature.

### Integrated Features
_(unchecked = awaiting documentation)_

- [x] Manual Initialization - *This is required now in StaticCMS for both CDN and Bundling setups. Simply call `CMS.init()`*
- [x] Working with a Local Git
- [x] List Widget: Variable Types
- [x] Folder Collections Media and Public Folder #64 

### Will Integrate Later
_These features will be fully tested and integrated after 1.0.0 Release. Until then they will remain in beta status, as they have not been fully tested and may potentially be completely broken or not work as intended._

- [x] i18n Support #62 
- [x] Nested Collections #63
- [x] Folder Collections Path #64 
- [x] Summary string template transformations #227
- [x] Registering to CMS Events #228
- [x] Commit Message Templates #230
- [x] Image widget file size limit #229

### Dropped Features
- [x] ~~Remark plugins~~ *Dropping as new markdown editor has its own plugin system.*
- [x] ~~GraphQL Support for GitHub and GitLab~~ *Dropping in favor of reducing code complexity. Will revisit if needed.*
- [x] ~~Custom Mount Element~~
- [x] ~~Dynamic Default Values~~

**Comment by onodera-punpun** [comment]
I would be really happy if the 'relative image paths' option from 'Folder Collections Media and Public Folder' could be kept, as I store my images not in a big static folder in the root, but relative to the markdownfile of an article.

**Comment by KaneFreeman** [comment]
> I would be really happy if the 'relative image paths' option from 'Folder Collections Media and Public Folder' could be kept, as I store my images not in a big static folder in the root, but relative to the markdownfile of an article.

Yeah that one will most likely stay. Honestly most of the beta features are small and thus do not add much to the maintainability of the project. So most them will stay.

**Comment by KaneFreeman** [comment]
> Commit Message Templates, Registering to CMS Events, Summary string template transformations are all pretty handy
> 
> We use Commit Message Templates to skip CI for certain types of updates
> 
> Also CMS Events are nice for massaging data to exact shape you want to persist & setting dynamic default values

Yeah I will probably be keeping all 3 of those. I use `Summary string template transformations` in one of my own projects so that is definitely staying.

Basically it its something small (which those 3 definitely are), works well as is and isn't a nightmare to maintain it will probably stay.
